exclude_patterns = [
  "*_min.*",
  "*-min.*",
  "*.min.*",
  "**/.yarn/**",
  "**/*.d.ts",
  "**/assets/**",
  "**/bower_components/**",
  "**/build/**",
  "**/cache/**",
  "**/config/**",
  "**/db/**",
  "**/deps/**",
  "**/dist/**",
  "**/extern/**",
  "**/external/**",
  "**/generated/**",
  "**/Godeps/**",
  "**/gradlew/**",
  "**/mvnw/**",
  "**/node_modules/**",
  "**/protos/**",
  "**/seed/**",
  "**/target/**",
  "**/templates/**",
  "**/testdata/**",
  "**/vendor/**",
]

test_patterns = [
  "**/tests/**",
  "**/workbench/**",
  "**/spec/**",
  "**/*.test.*",
  "**/*.spec.*",
  "**/*_test.*",
  "**/*_spec.*",
  "**/test_*.*",
  "**/spec_*.*",
]

[project]
name = "laravel-passport-modern-scopes"
language = "php"
coverage = true

[coverage]
report = "coverage/clover.xml"
tool = "phpunit"


[analyze]
enabled = true

[similar_code]
exclude_patterns = [
  "**/tests/**",
  "**/workbench/**",
  "**/dist/**",
  "**/vendor/**",
  "**/docs/**",
  "**/public/**",
  "**/database/**",
  "**/lang/**",
  "**/config/**",
]

[files]
include = ["src/"]
exclude = [
  "vendor/**",
  "tests/**",
  "workbench/**",
  "dist/**",
  "node_modules/**",
  "**/database/**",
  "**/lang/**",
  "**/config/**",
]


